# Конфигурация сервера
server:
  port: 8081

# Конфигурация Spring Boot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qasqir_inventory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC+5
    username: postgres
    password: erke
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com       # SMTP-сервер Gmail
    port: 587                  # Порт для STARTTLS
    username: tmqasqirinventory@gmail.com   # Ваш адрес Gmail
    password: lhvmohlhvtovxykt  # Пароль приложения
    from: "Noreply <tmqasqirinventory@gmail.com>"
    properties:
      mail.smtp.auth: true      # Включение аутентификации
      mail.smtp.starttls.enable: true  # Включение STARTTLS
  jackson:
    time-zone: Asia/Aqtobe



# Конфигурация Flyway
flyway:
  enabled: true
  locations: classpath:db/migration

# Настройки безопасности приложения
app:
  security:
    salt-rounds: 12
  superadmins:
    - username: SuperAdmin1
      password: ENC($2a$12$W3qpaw./1DZy/t3elNdtjeo.rttSOnPWywU.8tdOuWgTwNGIWvmhq)
    - username: SuperAdmin2
      password: ENC($2a$12$TxN7SBjj.MbnlQz9mnDA2e8dbEq7bZsPH5P7cNBKlukBnq3VukVFW)

# Настройки документации API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Роли пользователей
userRoles:
  admin: admin
  warehouse_manager: warehouse_manager
  storekeeper: storekeeper
  employee: employee

api:
  path:
    admin: /api/v1/admin
    warehouse_manager: /api/v1/warehouse-manager
    storekeeper: /api/v1/storekeeper
    employee: /api/v1/employee

# Ссылка для приглашений
invite:
  link: http://localhost:5173/recover-password

password-recovery:
  link: http://localhost:5173/

image:
  directory:
    link: "E:/AAAAWORK/Work/imageQasqir/"

company:
  data:
    support-email: "office@alioth.kz"
    support-phone: "+7 708 652 94 60"
    company-contact-info: "TOO ALIOTH, TM QasQir, ул. Торгут Озала 161, г. Алматы"


# Логирование
logging:
  level:
    org.springframework.mail: ERROR            # Отключение логов для почтовых операций в Spring
    org.apache.commons.mail: ERROR             # Отключение логов для Apache Commons Mail (если используется)
    org.hibernate.SQL: DEBUG                # Логирование SQL-запросов (по желанию)
    org.flywaydb: DEBUG                      # Логирование Flyway миграций (если необходимо)



bitrix24:
  webhook-url: "https://b24-mvtnvt.bitrix24.kz/rest/1/n7jy59tgz5tnu571/"



servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
