# Конфигурация сервера
server:
#  address: 0.0.0.0
  port: 8081

# Конфигурация Spring Boot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qasqir_inventory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC+5
    username: postgres
    password: erke
#  spring:
#    datasource:
#      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/qasqir_inventory}
#      username: ${SPRING_DATASOURCE_USERNAME:postgres}
#      password: ${SPRING_DATASOURCE_PASSWORD:erke}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tmqasqirinventory@gmail.com
    password: lhvmohlhvtovxykt
    from: "Noreply <tmqasqirinventory@gmail.com>"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Aqtobe
  cache:
    jcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Конфигурация Flyway
flyway:
  enabled: true
  locations: classpath:db/migration

# Настройки безопасности приложения
app:
  security:
    salt-rounds: 12
  superadmins:
    - username: SuperAdmin1
      password: ENC($2a$12$W3qpaw./1DZy/t3elNdtjeo.rttSOnPWywU.8tdOuWgTwNGIWvmhq)
    - username: SuperAdmin2
      password: ENC($2a$12$TxN7SBjj.MbnlQz9mnDA2e8dbEq7bZsPH5P7cNBKlukBnq3VukVFW)

# Настройки документации API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Роли пользователей
userRoles:
  admin: admin
  warehouse_manager: warehouse_manager
  storekeeper: storekeeper
  employee: employee
  oneC: one_c

api:
  path:
    admin: /api/v1/admin
    warehouse_manager: /api/v1/warehouse-manager
    storekeeper: /api/v1/storekeeper
    employee: /api/v1/employee
    oneC: /api/v1/1C

# Ссылка для приглашений и восстановления пароля
invite:
  link: http://localhost:5173/recover-password

password-recovery:
  link: http://localhost:5173/reset-password

image:
  directory:
    link: "C:/WORK/image/"

company:
  data:
    support-email: "office@alioth.kz"
    support-phone: "+7 708 652 94 60"
    company-contact-info: "TOO ALIOTH, TM QasQir, ул. Торгут Озала 161, г. Алматы"

# Логирование
logging:
  level:
    org.springframework.mail: ERROR
    org.apache.commons.mail: ERROR
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
    org.springframework.web: INFO  # Добавлено для уменьшения лишних логов

bitrix24:
  webhook-url: "https://b24-mvtnvt.bitrix24.kz/rest/1/n7jy59tgz5tnu571/"


file:
  directory:
    link: "C:/WORK/file/"