# Конфигурация сервера
server:
  port: 8081

# Конфигурация Spring Boot
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qasqir_inventory?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: erke
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com       # SMTP-сервер Gmail
    port: 587                  # Порт для STARTTLS
    username: tmqasqirinventory@gmail.com   # Ваш адрес Gmail
    password: lhvmohlhvtovxykt  # Пароль приложения
    properties:
      mail.smtp.auth: true      # Включение аутентификации
      mail.smtp.starttls.enable: true  # Включение STARTTLS


# Конфигурация Flyway
flyway:
  enabled: true
  locations: classpath:db/migration

# Настройки безопасности приложения
app:
  security:
    salt-rounds: 12
  superadmins:
    - username: SuperAdmin1
      password: ENC($2a$12$W3qpaw./1DZy/t3elNdtjeo.rttSOnPWywU.8tdOuWgTwNGIWvmhq)
    - username: SuperAdmin2
      password: ENC($2a$12$TxN7SBjj.MbnlQz9mnDA2e8dbEq7bZsPH5P7cNBKlukBnq3VukVFW)

# Настройки документации API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Роли пользователей
userRoles:
  company_admin: company_admin
  super_admin: super_admin

# API пути
api:
  path:
    admin: /api/v1/admin
    super_admin: /api/v1/super-admin

# Роли пользователей с ID
roleIds:
  employee: 1
  admin: 2

# Ссылка для приглашений
invite:
  link: http://localhost:5173/recover-password

# Логирование
logging:
  level:
    org.flywaydb: DEBUG