---- Удаление базы данных, если она существует
--DROP DATABASE IF EXISTS qasqir_inventory;
--
---- Создание новой базы данных
--CREATE DATABASE qasqir_inventory;
--
---- Подключение к новой базе данных
--\c qasqir_inventory
--
---- Создание таблицы t_organizations
--CREATE TABLE t_organizations
--(
--    id                  SERIAL          NOT NULL,
--    organization_name   VARCHAR(50)     NOT NULL,
--    admin_mail          VARCHAR(50)     NOT NULL,
--    PRIMARY KEY (id),
--    UNIQUE (organization_name) -- Уникальный индекс на поле organization_name
--);
--
---- Создание индекса на поле admin_mail
--CREATE INDEX idx_organizations_admin_mail ON t_organizations (admin_mail);
--
---- Создание таблицы t_users
--CREATE TABLE t_users
--(
--    id                  SERIAL          NOT NULL,
--    user_name           VARCHAR(20)     NOT NULL,
--    password            VARCHAR(256)    NOT NULL,
--    email               VARCHAR(70)     NOT NULL,
--    email_verified      BOOLEAN         NOT NULL,
--    organization_id     INT             NOT NULL,
--    PRIMARY KEY (id),
--    FOREIGN KEY (organization_id) REFERENCES t_organizations (id)
--);
--
---- Создание индексов на поля user_name и email
--CREATE INDEX idx_users_user_name ON t_users (user_name);
--CREATE INDEX idx_users_email ON t_users (email);
--
---- Создание таблицы t_sessions
--CREATE TABLE t_sessions
--(
--    id          SERIAL                  NOT NULL,
--    expiration  TIMESTAMP               NOT NULL,
--    token       VARCHAR(256)            NOT NULL,
--    user_id     INT                     NOT NULL,
--    PRIMARY KEY (id),
--    FOREIGN KEY (user_id) REFERENCES t_users (id)
--);
--
---- Создание индекса на поле token
--CREATE INDEX idx_sessions_token ON t_sessions (token);
--
---- Создание таблицы t_roles
--CREATE TABLE t_roles
--(
--    id          SERIAL                  NOT NULL,
--    role_name   VARCHAR(20)             NOT NULL,
--    PRIMARY KEY (id)
--);
--
---- Создание индекса на поле role_name
--CREATE INDEX idx_roles_role_name ON t_roles (role_name);
--
---- Создание таблицы t_user_roles
--CREATE TABLE t_user_roles
--(
--    id          SERIAL                  NOT NULL,
--    user_id     INT                     NOT NULL,
--    role_id     INT                     NOT NULL,
--    PRIMARY KEY (id),
--    FOREIGN KEY (user_id) REFERENCES t_users (id),
--    FOREIGN KEY (role_id) REFERENCES t_roles (id)
--);
--
---- Создание индексов на поля user_id и role_id
--CREATE INDEX idx_user_roles_user_id ON t_user_roles (user_id);
--CREATE INDEX idx_user_roles_role_id ON t_user_roles (role_id);
--
---- Создание таблицы t_mail_verifications
--CREATE TABLE t_mail_verifications
--(
--    id              SERIAL              NOT NULL,
--    email           VARCHAR(70)         NOT NULL,
--    code            VARCHAR(6)          NOT NULL,
--    PRIMARY KEY(id)
--);
--
---- Создание индекса на поле email
--CREATE INDEX idx_mail_verifications_email ON t_mail_verifications (email);
--
---- Создание таблицы t_invites
--CREATE TABLE t_invites
--(
--    id              SERIAL              NOT NULL,
--    token           VARCHAR(256)        NOT NULL,
--    link            VARCHAR(255)        NOT NULL,
--    date_create     TIMESTAMP           NOT NULL,
--    expiration      TIMESTAMP           NOT NULL,
--    user_id         INT                 NOT NULL,
--    PRIMARY KEY(id),
--    FOREIGN KEY (user_id) REFERENCES t_users (id)
--);
--
---- Создание индексов на поля token и user_id
--CREATE INDEX idx_invites_token ON t_invites (token);
--CREATE INDEX idx_invites_user_id ON t_invites (user_id);
--
---- Создание таблицы t_organization_admins
--CREATE TABLE t_organization_admins
--(
--    id                  SERIAL          NOT NULL,
--    user_id             INT             NOT NULL,
--    organization_id     INT             NOT NULL,
--    PRIMARY KEY (id),
--    FOREIGN KEY (user_id) REFERENCES t_users (id),
--    FOREIGN KEY (organization_id) REFERENCES t_organizations (id)
--);
--
---- Создание индексов на поля user_id и organization_id
--CREATE INDEX idx_organization_admins_user_id ON t_organization_admins (user_id);
--CREATE INDEX idx_organization_admins_organization_id ON t_organization_admins (organization_id);
