ALTER TABLE t_warehouse_zones
ADD COLUMN width DECIMAL(20,10),
ADD COLUMN height DECIMAL(20,10),
ADD COLUMN length DECIMAL(20,10),
ADD COLUMN capacity DECIMAL(20,10),
ADD COLUMN can_store_items BOOLEAN DEFAULT TRUE;

