-- CREATE OR REPLACE VIEW view_zone_fill_percentage AS
-- SELECT
--     CASE
--         WHEN total_volume = 0 THEN 0
--         ELSE ROUND((used_capacity * 100.0 / total_volume)::numeric, 2)
--         END AS zone_fill_percentage
-- FROM (
--          SELECT
--              COALESCE(SUM(wz.length::numeric * wz.width::numeric * wz.height::numeric), 0) AS total_volume,
--              COALESCE(SUM(
--                               CASE
--                                   WHEN n.volume IS NOT NULL THEN n.volume::numeric * i.quantity
--                               WHEN n.height IS NOT NULL AND n.width IS NOT NULL AND n.length IS NOT NULL
--                               THEN n.height::numeric * n.width::numeric * n.length::numeric * i.quantity
--                               ELSE 0
--                               END
--                       ), 0) AS used_capacity
--          FROM t_warehouse_zones wz
--                   LEFT JOIN t_inventory i ON i.warehouse_zone_id = wz.id
--                   LEFT JOIN t_nomenclatures n ON i.nomenclature_id = n.id
--          WHERE wz.can_store_items = TRUE
--      ) AS volumes;
--
--
